# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - "4000:4000"
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve -H 0.0.0.0 --livereload --force_polling